paths:
  /api/products:
    get:
      summary: Devuelve los productos que creados hasta el momento
      tags:
        - Products
      responses:
        "200":
          description: Los productos se obtienen
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error interno, en este endpoint se deberá a un error en la base de datos o no está logueado
    post:
      summary: Crea un nuevo producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBody/UpdateProduct"
      resonses:
        "200":
          description: Producto creado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error interno, en este endpoint se deberá a un error en la base de datos
  /api/products/{pid}:
    get:
      summary: Obtiene el producto a través de un ID proporcionado
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: id para obtener el producto
          schema:
            type: string
      responses:
        "200":
          description: El producto encontrado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "400":
          description: Error interno, en este endpoint se deberá a un error en la base de datos o no está logueado
    put:
      summary: Modifica los productos
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: id para obtener el producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBody/UpdateProduct"
      resonses:
        "200":
          description: Producto modificado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: Error interno, en este endpoint se deberá a un error en la base de datos
    delete:
      summary: Elimina los productos
      tags:
        - Products
components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          description: Tipo de producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnail:
          type: array
          description: Imagen del producto
        code:
          type: string
          description: Codigo único identificatorio del producto
        status:
          type: boolean
          description: Confirma si el producto está disponible o no
        stock:
          type: string
          description: Cantidad de productos disponibles
        owner:
          type: string
          description: email del usuario que crea el producto
        _id:
          type: string
          description: Id autogenerado por la base de datos
      example:
        _id: ObjectId("sdasdasdas")
        type: Remera
        description: Pearl Jam
        price: 100,
        thumbnail:
          [
            "https://d3ugyf2ht6aenh.cloudfront.net/stores/402/355/products/pabluchy_remeras_catalogo_hombre_m110spinetta1-2e8bf12bbedd8e88c415381554185971-640-0.png",
          ]
        code: 7
        status: true
        stock: 100
        owner: mail@coder.com
  requestBody:
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: Nuevo tipo de producto
        description:
          type: string
          description: Nueva descripción del producto
        price:
          type: number
          description: Nuevo precio del producto
        thumbnail:
          type: array
          description: Nueva imagen del producto
        status:
          type: boolean
          description: Cambiar disponibilidad del producto
        stock:
          type: string
          description: Nueva cantidad de productos disponibles
      example:
        _id: ObjectId("sdasdasdas")
        title: Remera
        description: Pearl Jam
        price: 100,
        thumbnail:
          [
            "https://d3ugyf2ht6aenh.cloudfront.net/stores/402/355/products/pabluchy_remeras_catalogo_hombre_m110spinetta1-2e8bf12bbedd8e88c415381554185971-640-0.png",
          ]
        code: 7
        status: true
        stock: 100
        owner: mail@coder.com
    